More logs
BarakHaver/dynalite pull request #7
Opened 2016-11-16 13:37 UTC by davidlevanon

2016-11-17 13:07 UTC, dor-levi requested changes

2016-11-17 13:07 UTC, dor-levi commented on index.js
> +			logger.info("Process Memroy Stats: " + stringify(process.memoryUsage()));
Can `stringify(process.memoryUsage())` fail?

Probably should surround this with try/catch

2016-11-17 13:07 UTC, dor-levi commented on index.js
> +			if (action == "createTable") {
I don't fully understand the purpose of this if statement

2016-11-17 13:07 UTC, dor-levi commented on index.js
> +		tableName = "error";
Not sure tableName should be overridden here

2016-11-17 13:07 UTC, dor-levi commented on logger/index.js
> +				level: "debug"
Do we want level param to be configurable?

2016-11-17 13:17 UTC, davidlevanon commented on logger/index.js
> +				level: "debug"
We don't always use logger in our "dynalite". But, when we use it we put "debug" to see everything. 

Look at the "if (!opts.verbose) {" in the beginning of the method.

2016-11-17 13:26 UTC, dor-levi commented on logger/index.js
> +				level: "debug"
I've seen it, still wondered if we want this more configurable.
No is a valid answer :)

2016-11-17 15:19 UTC, dor-levi requested changes

2016-11-17 15:19 UTC, dor-levi commented on index.js
> +		details = stringify(data)
Missing `;`

2016-11-17 15:19 UTC, dor-levi commented on index.js
> +		details = stringify(data);
We might want to consider

```
if (data.TableName)
{
    tableName = data.TableName;
}
```

So we'll catch any actions we missed

2016-11-17 15:19 UTC, dor-levi commented on index.js
> +		if (data) {
can be `if ((action == "describeTable") && (data) && (data.Table)) {` to save some indentation and crash possibilities

2016-11-19 19:41 UTC, dor-levi approved these changes

2016-11-20 09:02 UTC, merged